---
log:
  level: debug
  json: false

server:
  addr: :3001
  read_timeout: 5s
  write_timeout: 15s
  shutdown_timeout: 10s
  cors_origins: http://localhost:4200,https://4200-ws-gferreux.cluster-ut4kyuiqi5d5suqbh6cuvr2cbg.cloudworkstations.dev

firestore:
  project_id: dmc-datastores-dev-becb
  database_id: dmc-data-loader-dev
  collection: load_config

auth:
  mode: none
  iap_audience: ""
