// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/adapter/auth"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/adapter/firestore"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/adapter/sftpgo"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/app"
	loadconfig2 "github.com/dekuple-labs/dmc-dataloader-api/internal/app/handler/loadconfig"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/app/handler/sftpaccount"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/domain/model"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/domain/usecase/loadconfig"
)

// Injectors from wire.go:

// InitializeApp wires the dependency graph and builds the application.
func InitializeApp(ctx context.Context, appConfig model.AppConfig) (*app.App, func(), error) {
	repository, cleanup, err := firestore.NewRepository(ctx, appConfig)
	if err != nil {
		return nil, nil, err
	}
	directory, cleanup2, err := firestore.NewDirectory(ctx, appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	deriveConfig := loadconfig.ProvideSettings(appConfig)
	logger := loadconfig.ProvideLogger()
	loadConfigUsecase := loadconfig.NewUsecase(repository, directory, deriveConfig, logger)
	handler := loadconfig2.NewHandler(loadConfigUsecase)
	service := sftpgo.ProvideService(appConfig, logger)
	sftpaccountHandler := sftpaccount.NewHandler(service)
	authenticator, err := auth.NewAuthenticator(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appApp := app.New(appConfig, handler, sftpaccountHandler, authenticator)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
