// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dekuple-labs/dmc-dataloader-api/internal/app"
	helloworld2 "github.com/dekuple-labs/dmc-dataloader-api/internal/app/handler/helloworld"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/domain/model"
	"github.com/dekuple-labs/dmc-dataloader-api/internal/domain/usecase/helloworld"
)

// Injectors from wire.go:

// InitializeApp wires the dependency graph and builds the application.
func InitializeApp(appConfig model.AppConfig) *app.App {
	helloWorldUsecase := helloworld.NewHelloWorldUsecase()
	handler := helloworld2.NewHandler(helloWorldUsecase)
	appApp := app.New(appConfig, handler)
	return appApp
}
